# Cloud Build configuration for Dino Backend
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/dino-repo/dino-backend:$BUILD_ID',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/dino-repo/dino-backend:latest',
      '.'
    ]

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/$PROJECT_ID/dino-repo/dino-backend:$BUILD_ID'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'dino-backend',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/dino-repo/dino-backend:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--concurrency', '80',
      '--timeout', '300',
      '--port', '8080',
      '--set-env-vars', 'ENVIRONMENT=production,GCP_PROJECT_ID=$PROJECT_ID,DATABASE_NAME=(default),GCS_BUCKET_NAME=$PROJECT_ID-dino-storage,QR_CODE_BASE_URL=https://dino-backend-$PROJECT_ID.a.run.app,CORS_ORIGINS=https://dino-frontend-$PROJECT_ID.a.run.app,SECRET_KEY=${_JWT_SECRET}',
      '--service-account', 'dino-backend-sa@$PROJECT_ID.iam.gserviceaccount.com'
    ]

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Images to be pushed to registry
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/dino-repo/dino-backend:$BUILD_ID'